-- ServiceLoader in ServerScriptService

local GameRoomInitializer = require(game.ServerScriptService.Controller.GameRoomInitializer)

local InventoryService = require(game.ServerScriptService.Service.InventoryService)
local PlayerDataService = require(game.ServerScriptService.Service.PlayerDataService)
local CoinAreaService = require(game.ServerScriptService.Service.CoinAreaService)
local BarrelSystemService = require(game.ServerScriptService.Service.BarrelSystemService.BarrelSystemService)
